// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMonthAuditLogs = `-- name: ListMonthAuditLogs :many
SELECT id, user_id, username, action, entity, entity_id, timestamp, details
FROM audit_logs
WHERE timestamp >= date_trunc('month', $1)
  AND timestamp < date_trunc('month', $1) + INTERVAL '1 month'
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListMonthAuditLogsParams struct {
	DateTrunc pgtype.Interval `json:"date_trunc"`
	Limit     int32           `json:"limit"`
	Offset    int32           `json:"offset"`
}

func (q *Queries) ListMonthAuditLogs(ctx context.Context, arg ListMonthAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listMonthAuditLogs, arg.DateTrunc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Timestamp,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAudit = `-- name: LogAudit :exec
INSERT INTO audit_logs (user_id, username, action, entity, entity_id, details)
VALUES ($1, $2, $3, $4, $5, $6)
`

type LogAuditParams struct {
	UserID   pgtype.Int4 `json:"user_id"`
	Username pgtype.Text `json:"username"`
	Action   string      `json:"action"`
	Entity   string      `json:"entity"`
	EntityID pgtype.Int4 `json:"entity_id"`
	Details  []byte      `json:"details"`
}

func (q *Queries) LogAudit(ctx context.Context, arg LogAuditParams) error {
	_, err := q.db.Exec(ctx, logAudit,
		arg.UserID,
		arg.Username,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Details,
	)
	return err
}
