// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchCreateMaterials implements pgx.CopyFromSource.
type iteratorForBatchCreateMaterials struct {
	rows                 []BatchCreateMaterialsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchCreateMaterials) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchCreateMaterials) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Type,
		r.rows[0].Saleable,
		r.rows[0].UnitPrice,
		r.rows[0].SalePrice,
		r.rows[0].Category,
		r.rows[0].Code,
		r.rows[0].Sku,
		r.rows[0].Barcode,
		r.rows[0].MeasureUnitID,
		r.rows[0].Weight,
		r.rows[0].IsToxic,
		r.rows[0].IsFlammable,
		r.rows[0].IsFragile,
		r.rows[0].TaxRate,
		r.rows[0].IsActive,
	}, nil
}

func (r iteratorForBatchCreateMaterials) Err() error {
	return nil
}

func (q *Queries) BatchCreateMaterials(ctx context.Context, arg []BatchCreateMaterialsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"materials"}, []string{"name", "description", "type", "saleable", "unit_price", "sale_price", "category", "code", "sku", "barcode", "measure_unit_id", "weight", "is_toxic", "is_flammable", "is_fragile", "tax_rate", "is_active"}, &iteratorForBatchCreateMaterials{rows: arg})
}
