// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) AS count
FROM customers
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchCustomers = `-- name: CountSearchCustomers :one
SELECT COUNT(*) AS count
FROM customers
WHERE 
    ($1::TEXT IS NULL OR 
     name ILIKE '%' || $1 || '%' OR 
     contact_name ILIKE '%' || $1 || '%' OR 
     contact_email ILIKE '%' || $1 || '%' OR
     contact_phone ILIKE '%' || $1 || '%' OR
     address ILIKE '%' || $1 || '%')
`

func (q *Queries) CountSearchCustomers(ctx context.Context, query pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchCustomers, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, contact_name, contact_email, contact_phone, address, meta)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
`

type CreateCustomerParams struct {
	Name         string      `json:"name"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	Address      pgtype.Text `json:"address"`
	Meta         []byte      `json:"meta"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
		arg.Meta,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM customers
WHERE contact_email = $1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, contactEmail pgtype.Text) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, contactEmail)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int32) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByName = `-- name: GetCustomerByName :one
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM customers
WHERE name = $1
`

func (q *Queries) GetCustomerByName(ctx context.Context, name string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByName, name)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM customers
WHERE contact_phone = $1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, contactPhone pgtype.Text) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, contactPhone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM customers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Address,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM customers
WHERE 
    ($3::TEXT IS NULL OR 
     name ILIKE '%' || $3 || '%' OR 
     contact_name ILIKE '%' || $3 || '%' OR 
     contact_email ILIKE '%' || $3 || '%' OR
     contact_phone ILIKE '%' || $3 || '%' OR
     address ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type SearchCustomersParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Query  pgtype.Text `json:"query"`
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomers, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Address,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET
    name = COALESCE(NULLIF($2, ''), name),
    contact_name = COALESCE($3, contact_name),
    contact_email = COALESCE($4, contact_email),
    contact_phone = COALESCE($5, contact_phone),
    address = COALESCE($6, address),
    meta = COALESCE($7, meta),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID           int32       `json:"id"`
	Column2      interface{} `json:"column_2"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	Address      pgtype.Text `json:"address"`
	Meta         []byte      `json:"meta"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Column2,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
		arg.Meta,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
