// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MaterialType string

const (
	MaterialTypeRaw          MaterialType = "raw"
	MaterialTypeIntermediate MaterialType = "intermediate"
	MaterialTypeFinished     MaterialType = "finished"
	MaterialTypeConsumable   MaterialType = "consumable"
	MaterialTypeService      MaterialType = "service"
)

func (e *MaterialType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaterialType(s)
	case string:
		*e = MaterialType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaterialType: %T", src)
	}
	return nil
}

type NullMaterialType struct {
	MaterialType MaterialType `json:"material_type"`
	Valid        bool         `json:"valid"` // Valid is true if MaterialType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaterialType) Scan(value interface{}) error {
	if value == nil {
		ns.MaterialType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaterialType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaterialType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaterialType), nil
}

type StockDirection string

const (
	StockDirectionIN  StockDirection = "IN"
	StockDirectionOUT StockDirection = "OUT"
)

func (e *StockDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockDirection(s)
	case string:
		*e = StockDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for StockDirection: %T", src)
	}
	return nil
}

type NullStockDirection struct {
	StockDirection StockDirection `json:"stock_direction"`
	Valid          bool           `json:"valid"` // Valid is true if StockDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockDirection) Scan(value interface{}) error {
	if value == nil {
		ns.StockDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockDirection), nil
}

type StockMovementType string

const (
	StockMovementTypeOPENING         StockMovementType = "OPENING"
	StockMovementTypePURCHASERECEIPT StockMovementType = "PURCHASE_RECEIPT"
	StockMovementTypeSALE            StockMovementType = "SALE"
	StockMovementTypeCUSTOMERRETURN  StockMovementType = "CUSTOMER_RETURN"
	StockMovementTypeTRANSFERIN      StockMovementType = "TRANSFER_IN"
	StockMovementTypeTRANSFEROUT     StockMovementType = "TRANSFER_OUT"
	StockMovementTypeSCRAP           StockMovementType = "SCRAP"
	StockMovementTypeADJUSTMENTIN    StockMovementType = "ADJUSTMENT_IN"
	StockMovementTypeADJUSTMENTOUT   StockMovementType = "ADJUSTMENT_OUT"
)

func (e *StockMovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockMovementType(s)
	case string:
		*e = StockMovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for StockMovementType: %T", src)
	}
	return nil
}

type NullStockMovementType struct {
	StockMovementType StockMovementType `json:"stock_movement_type"`
	Valid             bool              `json:"valid"` // Valid is true if StockMovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.StockMovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockMovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockMovementType), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleManager UserRole = "manager"
	UserRoleUser    UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ValuationMethod string

const (
	ValuationMethodFIFO            ValuationMethod = "FIFO"
	ValuationMethodLIFO            ValuationMethod = "LIFO"
	ValuationMethodWeightedAverage ValuationMethod = "Weighted Average"
)

func (e *ValuationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ValuationMethod(s)
	case string:
		*e = ValuationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for ValuationMethod: %T", src)
	}
	return nil
}

type NullValuationMethod struct {
	ValuationMethod ValuationMethod `json:"valuation_method"`
	Valid           bool            `json:"valid"` // Valid is true if ValuationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullValuationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.ValuationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ValuationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullValuationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ValuationMethod), nil
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int4        `json:"user_id"`
	Username  pgtype.Text        `json:"username"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  pgtype.Int4        `json:"entity_id"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	Details   []byte             `json:"details"`
}

type Batch struct {
	ID              int32              `json:"id"`
	MaterialID      pgtype.Int4        `json:"material_id"`
	SupplierID      pgtype.Int4        `json:"supplier_id"`
	WarehouseID     pgtype.Int4        `json:"warehouse_id"`
	MovementID      pgtype.Int4        `json:"movement_id"`
	UnitPrice       pgtype.Numeric     `json:"unit_price"`
	BatchNumber     string             `json:"batch_number"`
	ManufactureDate pgtype.Date        `json:"manufacture_date"`
	ExpiryDate      pgtype.Date        `json:"expiry_date"`
	StartQuantity   pgtype.Numeric     `json:"start_quantity"`
	CurrentQuantity pgtype.Numeric     `json:"current_quantity"`
	Notes           pgtype.Text        `json:"notes"`
	Meta            []byte             `json:"meta"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type BillsOfMaterial struct {
	ID                   int32              `json:"id"`
	FinishedMaterialID   pgtype.Int4        `json:"finished_material_id"`
	ComponentMaterialID  pgtype.Int4        `json:"component_material_id"`
	Quantity             pgtype.Numeric     `json:"quantity"`
	UnitMeasureID        pgtype.Int4        `json:"unit_measure_id"`
	Meta                 []byte             `json:"meta"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	ScrapPercentage      pgtype.Numeric     `json:"scrap_percentage"`
	FixedQuantity        pgtype.Bool        `json:"fixed_quantity"`
	IsOptional           pgtype.Bool        `json:"is_optional"`
	Priority             pgtype.Int4        `json:"priority"`
	ReferenceDesignator  pgtype.Text        `json:"reference_designator"`
	Notes                pgtype.Text        `json:"notes"`
	EffectiveDate        pgtype.Date        `json:"effective_date"`
	ExpiryDate           pgtype.Date        `json:"expiry_date"`
	Version              pgtype.Text        `json:"version"`
	OperationSequence    pgtype.Int4        `json:"operation_sequence"`
	EstimatedCost        pgtype.Numeric     `json:"estimated_cost"`
	ActualCost           pgtype.Numeric     `json:"actual_cost"`
	LeadTimeDays         pgtype.Int4        `json:"lead_time_days"`
	SupplierID           pgtype.Int4        `json:"supplier_id"`
	AlternateComponentID pgtype.Int4        `json:"alternate_component_id"`
	IsActive             pgtype.Bool        `json:"is_active"`
	Archived             pgtype.Bool        `json:"archived"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	ArchivedBy           pgtype.Int4        `json:"archived_by"`
}

type Customer struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	ContactName  pgtype.Text        `json:"contact_name"`
	ContactEmail pgtype.Text        `json:"contact_email"`
	ContactPhone pgtype.Text        `json:"contact_phone"`
	Address      pgtype.Text        `json:"address"`
	Meta         []byte             `json:"meta"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Material struct {
	ID            int32               `json:"id"`
	Name          string              `json:"name"`
	Description   pgtype.Text         `json:"description"`
	Valuation     NullValuationMethod `json:"valuation"`
	Type          MaterialType        `json:"type"`
	Saleable      pgtype.Bool         `json:"saleable"`
	UnitPrice     pgtype.Numeric      `json:"unit_price"`
	SalePrice     pgtype.Numeric      `json:"sale_price"`
	Category      pgtype.Int4         `json:"category"`
	Code          string              `json:"code"`
	Sku           string              `json:"sku"`
	Barcode       pgtype.Text         `json:"barcode"`
	MeasureUnitID pgtype.Int4         `json:"measure_unit_id"`
	Weight        pgtype.Numeric      `json:"weight"`
	Volume        pgtype.Numeric      `json:"volume"`
	Density       pgtype.Numeric      `json:"density"`
	IsToxic       pgtype.Bool         `json:"is_toxic"`
	IsFlammable   pgtype.Bool         `json:"is_flammable"`
	IsFragile     pgtype.Bool         `json:"is_fragile"`
	ImageUrl      pgtype.Text         `json:"image_url"`
	DocumentUrl   pgtype.Text         `json:"document_url"`
	TaxRate       pgtype.Numeric      `json:"tax_rate"`
	DiscountRate  pgtype.Numeric      `json:"discount_rate"`
	IsActive      pgtype.Bool         `json:"is_active"`
	Archived      pgtype.Bool         `json:"archived"`
	Meta          []byte              `json:"meta"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `json:"updated_at"`
}

type MaterialCategory struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Meta        []byte             `json:"meta"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MeasureUnit struct {
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	Abbreviation     string             `json:"abbreviation"`
	ConvertionFactor pgtype.Numeric     `json:"convertion_factor"`
	ConvertTo        pgtype.Int4        `json:"convert_to"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PurchaseOrder struct {
	ID                   int32              `json:"id"`
	OrderNumber          string             `json:"order_number"`
	SupplierID           pgtype.Int4        `json:"supplier_id"`
	OrderDate            pgtype.Timestamptz `json:"order_date"`
	ExpectedDeliveryDate pgtype.Timestamptz `json:"expected_delivery_date"`
	Status               string             `json:"status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	CreatedBy            pgtype.Int4        `json:"created_by"`
	ApprovedBy           pgtype.Int4        `json:"approved_by"`
	Meta                 []byte             `json:"meta"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PurchaseOrderItem struct {
	ID               int32              `json:"id"`
	PurchaseOrderID  pgtype.Int4        `json:"purchase_order_id"`
	MaterialID       pgtype.Int4        `json:"material_id"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	TotalPrice       pgtype.Numeric     `json:"total_price"`
	ReceivedQuantity pgtype.Numeric     `json:"received_quantity"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrder struct {
	ID                   int32              `json:"id"`
	OrderNumber          string             `json:"order_number"`
	CustomerID           pgtype.Int4        `json:"customer_id"`
	OrderDate            pgtype.Timestamptz `json:"order_date"`
	ExpectedDeliveryDate pgtype.Timestamptz `json:"expected_delivery_date"`
	Status               string             `json:"status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	CreatedBy            pgtype.Int4        `json:"created_by"`
	ApprovedBy           pgtype.Int4        `json:"approved_by"`
	Meta                 []byte             `json:"meta"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type SalesOrderItem struct {
	ID              int32              `json:"id"`
	SalesOrderID    pgtype.Int4        `json:"sales_order_id"`
	MaterialID      pgtype.Int4        `json:"material_id"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	UnitPrice       pgtype.Numeric     `json:"unit_price"`
	TotalPrice      pgtype.Numeric     `json:"total_price"`
	ShippedQuantity pgtype.Numeric     `json:"shipped_quantity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type StockMovement struct {
	ID              int32              `json:"id"`
	MaterialID      pgtype.Int4        `json:"material_id"`
	FromWarehouseID pgtype.Int4        `json:"from_warehouse_id"`
	ToWarehouseID   pgtype.Int4        `json:"to_warehouse_id"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	StockDirection  StockDirection     `json:"stock_direction"`
	MovementType    StockMovementType  `json:"movement_type"`
	Reference       pgtype.Text        `json:"reference"`
	PerformedBy     pgtype.Int4        `json:"performed_by"`
	MovementDate    pgtype.Timestamptz `json:"movement_date"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Supplier struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	ContactName  pgtype.Text        `json:"contact_name"`
	ContactEmail pgtype.Text        `json:"contact_email"`
	ContactPhone pgtype.Text        `json:"contact_phone"`
	Address      pgtype.Text        `json:"address"`
	Meta         []byte             `json:"meta"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	Role         UserRole           `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VBomCostAnalysis struct {
	FinishedMaterialID    pgtype.Int4    `json:"finished_material_id"`
	FinishedMaterialName  pgtype.Text    `json:"finished_material_name"`
	FinishedMaterialCode  pgtype.Text    `json:"finished_material_code"`
	FinishedMaterialPrice pgtype.Numeric `json:"finished_material_price"`
	ComponentCount        int64          `json:"component_count"`
	RawMaterialCost       int64          `json:"raw_material_cost"`
	MaterialCostWithScrap int64          `json:"material_cost_with_scrap"`
	EstimatedTotalCost    int64          `json:"estimated_total_cost"`
	ActualTotalCost       int64          `json:"actual_total_cost"`
	MaxLeadTimeDays       interface{}    `json:"max_lead_time_days"`
	Version               pgtype.Text    `json:"version"`
}

type VEffectiveBom struct {
	ID                     int32              `json:"id"`
	FinishedMaterialID     pgtype.Int4        `json:"finished_material_id"`
	ComponentMaterialID    pgtype.Int4        `json:"component_material_id"`
	Quantity               pgtype.Numeric     `json:"quantity"`
	UnitMeasureID          pgtype.Int4        `json:"unit_measure_id"`
	Meta                   []byte             `json:"meta"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ScrapPercentage        pgtype.Numeric     `json:"scrap_percentage"`
	FixedQuantity          pgtype.Bool        `json:"fixed_quantity"`
	IsOptional             pgtype.Bool        `json:"is_optional"`
	Priority               pgtype.Int4        `json:"priority"`
	ReferenceDesignator    pgtype.Text        `json:"reference_designator"`
	Notes                  pgtype.Text        `json:"notes"`
	EffectiveDate          pgtype.Date        `json:"effective_date"`
	ExpiryDate             pgtype.Date        `json:"expiry_date"`
	Version                pgtype.Text        `json:"version"`
	OperationSequence      pgtype.Int4        `json:"operation_sequence"`
	EstimatedCost          pgtype.Numeric     `json:"estimated_cost"`
	ActualCost             pgtype.Numeric     `json:"actual_cost"`
	LeadTimeDays           pgtype.Int4        `json:"lead_time_days"`
	SupplierID             pgtype.Int4        `json:"supplier_id"`
	AlternateComponentID   pgtype.Int4        `json:"alternate_component_id"`
	IsActive               pgtype.Bool        `json:"is_active"`
	Archived               pgtype.Bool        `json:"archived"`
	ArchivedAt             pgtype.Timestamptz `json:"archived_at"`
	ArchivedBy             pgtype.Int4        `json:"archived_by"`
	FinishedMaterialName   pgtype.Text        `json:"finished_material_name"`
	FinishedMaterialCode   pgtype.Text        `json:"finished_material_code"`
	ComponentMaterialName  pgtype.Text        `json:"component_material_name"`
	ComponentMaterialCode  pgtype.Text        `json:"component_material_code"`
	ComponentUnitPrice     pgtype.Numeric     `json:"component_unit_price"`
	UnitName               pgtype.Text        `json:"unit_name"`
	UnitAbbreviation       pgtype.Text        `json:"unit_abbreviation"`
	SupplierName           pgtype.Text        `json:"supplier_name"`
	AlternateComponentName pgtype.Text        `json:"alternate_component_name"`
	AlternateComponentCode pgtype.Text        `json:"alternate_component_code"`
	AdjustedQuantity       int32              `json:"adjusted_quantity"`
	CalculatedCost         pgtype.Numeric     `json:"calculated_cost"`
}

type Warehouse struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	Code            string             `json:"code"`
	Location        pgtype.Text        `json:"location"`
	Description     pgtype.Text        `json:"description"`
	Valuation       ValuationMethod    `json:"valuation"`
	ParentWarehouse pgtype.Int4        `json:"parent_warehouse"`
	Capacity        pgtype.Numeric     `json:"capacity"`
	Meta            []byte             `json:"meta"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
