// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSalesOrders = `-- name: CountSalesOrders :one
SELECT COUNT(*) AS count
FROM sales_orders
`

func (q *Queries) CountSalesOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchSalesOrders = `-- name: CountSearchSalesOrders :one
SELECT COUNT(*) AS count
FROM sales_orders
WHERE 
    ($1::TEXT IS NULL OR 
     order_number ILIKE '%' || $1 || '%' OR 
     status ILIKE '%' || $1 || '%')
`

func (q *Queries) CountSearchSalesOrders(ctx context.Context, query pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchSalesOrders, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one
INSERT INTO sales_orders (order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta, created_at, updated_at
`

type CreateSalesOrderParams struct {
	OrderNumber          string             `json:"order_number"`
	CustomerID           pgtype.Int4        `json:"customer_id"`
	OrderDate            pgtype.Timestamptz `json:"order_date"`
	ExpectedDeliveryDate pgtype.Timestamptz `json:"expected_delivery_date"`
	Status               string             `json:"status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	CreatedBy            pgtype.Int4        `json:"created_by"`
	ApprovedBy           pgtype.Int4        `json:"approved_by"`
	Meta                 []byte             `json:"meta"`
}

func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.OrderNumber,
		arg.CustomerID,
		arg.OrderDate,
		arg.ExpectedDeliveryDate,
		arg.Status,
		arg.TotalAmount,
		arg.CreatedBy,
		arg.ApprovedBy,
		arg.Meta,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesOrderItem = `-- name: CreateSalesOrderItem :one
INSERT INTO sales_order_items (sales_order_id, material_id, quantity, unit_price, total_price, shipped_quantity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, sales_order_id, material_id, quantity, unit_price, total_price, shipped_quantity, created_at, updated_at
`

type CreateSalesOrderItemParams struct {
	SalesOrderID    pgtype.Int4    `json:"sales_order_id"`
	MaterialID      pgtype.Int4    `json:"material_id"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	TotalPrice      pgtype.Numeric `json:"total_price"`
	ShippedQuantity pgtype.Numeric `json:"shipped_quantity"`
}

func (q *Queries) CreateSalesOrderItem(ctx context.Context, arg CreateSalesOrderItemParams) (SalesOrderItem, error) {
	row := q.db.QueryRow(ctx, createSalesOrderItem,
		arg.SalesOrderID,
		arg.MaterialID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
		arg.ShippedQuantity,
	)
	var i SalesOrderItem
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.MaterialID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.ShippedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSalesOrder = `-- name: DeleteSalesOrder :exec
DELETE FROM sales_orders
WHERE id = $1
`

func (q *Queries) DeleteSalesOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSalesOrder, id)
	return err
}

const deleteSalesOrderItem = `-- name: DeleteSalesOrderItem :exec
DELETE FROM sales_order_items
WHERE id = $1
`

func (q *Queries) DeleteSalesOrderItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSalesOrderItem, id)
	return err
}

const getSalesOrderByID = `-- name: GetSalesOrderByID :one
SELECT id, order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta, created_at, updated_at
FROM sales_orders
WHERE id = $1
`

func (q *Queries) GetSalesOrderByID(ctx context.Context, id int32) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrderByID, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesOrderByOrderNumber = `-- name: GetSalesOrderByOrderNumber :one
SELECT id, order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta, created_at, updated_at
FROM sales_orders
WHERE order_number = $1
`

func (q *Queries) GetSalesOrderByOrderNumber(ctx context.Context, orderNumber string) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, getSalesOrderByOrderNumber, orderNumber)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesOrderItemByID = `-- name: GetSalesOrderItemByID :one
SELECT id, sales_order_id, material_id, quantity, unit_price, total_price, shipped_quantity, created_at, updated_at
FROM sales_order_items
WHERE id = $1
`

func (q *Queries) GetSalesOrderItemByID(ctx context.Context, id int32) (SalesOrderItem, error) {
	row := q.db.QueryRow(ctx, getSalesOrderItemByID, id)
	var i SalesOrderItem
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.MaterialID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.ShippedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSalesOrderItems = `-- name: ListSalesOrderItems :many
SELECT id, sales_order_id, material_id, quantity, unit_price, total_price, shipped_quantity, created_at, updated_at
FROM sales_order_items
WHERE sales_order_id = $1
ORDER BY id
`

func (q *Queries) ListSalesOrderItems(ctx context.Context, salesOrderID pgtype.Int4) ([]SalesOrderItem, error) {
	rows, err := q.db.Query(ctx, listSalesOrderItems, salesOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrderItem{}
	for rows.Next() {
		var i SalesOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.SalesOrderID,
			&i.MaterialID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.ShippedQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many
SELECT id, order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta, created_at, updated_at
FROM sales_orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSalesOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.CustomerID,
			&i.OrderDate,
			&i.ExpectedDeliveryDate,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrdersByCustomer = `-- name: ListSalesOrdersByCustomer :many
SELECT id, order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta, created_at, updated_at
FROM sales_orders
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSalesOrdersByCustomerParams struct {
	CustomerID pgtype.Int4 `json:"customer_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListSalesOrdersByCustomer(ctx context.Context, arg ListSalesOrdersByCustomerParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrdersByCustomer, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.CustomerID,
			&i.OrderDate,
			&i.ExpectedDeliveryDate,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrdersByStatus = `-- name: ListSalesOrdersByStatus :many
SELECT id, order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta, created_at, updated_at
FROM sales_orders
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSalesOrdersByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListSalesOrdersByStatus(ctx context.Context, arg ListSalesOrdersByStatusParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, listSalesOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.CustomerID,
			&i.OrderDate,
			&i.ExpectedDeliveryDate,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSalesOrders = `-- name: SearchSalesOrders :many
SELECT id, order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta, created_at, updated_at
FROM sales_orders
WHERE 
    ($3::TEXT IS NULL OR 
     order_number ILIKE '%' || $3 || '%' OR 
     status ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type SearchSalesOrdersParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Query  pgtype.Text `json:"query"`
}

func (q *Queries) SearchSalesOrders(ctx context.Context, arg SearchSalesOrdersParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, searchSalesOrders, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.CustomerID,
			&i.OrderDate,
			&i.ExpectedDeliveryDate,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSalesOrder = `-- name: UpdateSalesOrder :one
UPDATE sales_orders
SET
    order_number = COALESCE(NULLIF($2, ''), order_number),
    customer_id = COALESCE($3, customer_id),
    order_date = COALESCE($4, order_date),
    expected_delivery_date = COALESCE($5, expected_delivery_date),
    status = COALESCE(NULLIF($6, ''), status),
    total_amount = COALESCE($7, total_amount),
    approved_by = COALESCE($8, approved_by),
    meta = COALESCE($9, meta),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, order_number, customer_id, order_date, expected_delivery_date, status, total_amount, created_by, approved_by, meta, created_at, updated_at
`

type UpdateSalesOrderParams struct {
	ID                   int32              `json:"id"`
	Column2              interface{}        `json:"column_2"`
	CustomerID           pgtype.Int4        `json:"customer_id"`
	OrderDate            pgtype.Timestamptz `json:"order_date"`
	ExpectedDeliveryDate pgtype.Timestamptz `json:"expected_delivery_date"`
	Column6              interface{}        `json:"column_6"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	ApprovedBy           pgtype.Int4        `json:"approved_by"`
	Meta                 []byte             `json:"meta"`
}

func (q *Queries) UpdateSalesOrder(ctx context.Context, arg UpdateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, updateSalesOrder,
		arg.ID,
		arg.Column2,
		arg.CustomerID,
		arg.OrderDate,
		arg.ExpectedDeliveryDate,
		arg.Column6,
		arg.TotalAmount,
		arg.ApprovedBy,
		arg.Meta,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSalesOrderItem = `-- name: UpdateSalesOrderItem :one
UPDATE sales_order_items
SET
    material_id = COALESCE($2, material_id),
    quantity = COALESCE($3, quantity),
    unit_price = COALESCE($4, unit_price),
    total_price = COALESCE($5, total_price),
    shipped_quantity = COALESCE($6, shipped_quantity),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, sales_order_id, material_id, quantity, unit_price, total_price, shipped_quantity, created_at, updated_at
`

type UpdateSalesOrderItemParams struct {
	ID              int32          `json:"id"`
	MaterialID      pgtype.Int4    `json:"material_id"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	TotalPrice      pgtype.Numeric `json:"total_price"`
	ShippedQuantity pgtype.Numeric `json:"shipped_quantity"`
}

func (q *Queries) UpdateSalesOrderItem(ctx context.Context, arg UpdateSalesOrderItemParams) (SalesOrderItem, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderItem,
		arg.ID,
		arg.MaterialID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
		arg.ShippedQuantity,
	)
	var i SalesOrderItem
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.MaterialID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.ShippedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSalesOrderItemShippedQuantity = `-- name: UpdateSalesOrderItemShippedQuantity :one
UPDATE sales_order_items
SET
    shipped_quantity = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, sales_order_id, material_id, quantity, unit_price, total_price, shipped_quantity, created_at, updated_at
`

type UpdateSalesOrderItemShippedQuantityParams struct {
	ID              int32          `json:"id"`
	ShippedQuantity pgtype.Numeric `json:"shipped_quantity"`
}

func (q *Queries) UpdateSalesOrderItemShippedQuantity(ctx context.Context, arg UpdateSalesOrderItemShippedQuantityParams) (SalesOrderItem, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderItemShippedQuantity, arg.ID, arg.ShippedQuantity)
	var i SalesOrderItem
	err := row.Scan(
		&i.ID,
		&i.SalesOrderID,
		&i.MaterialID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
		&i.ShippedQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
