// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchSuppliers = `-- name: CountSearchSuppliers :one
SELECT COUNT(*) AS count
FROM suppliers
WHERE 
    ($1::TEXT IS NULL OR 
     name ILIKE '%' || $1 || '%' OR 
     contact_name ILIKE '%' || $1 || '%' OR 
     contact_email ILIKE '%' || $1 || '%' OR
     contact_phone ILIKE '%' || $1 || '%' OR
     address ILIKE '%' || $1 || '%')
`

func (q *Queries) CountSearchSuppliers(ctx context.Context, query pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchSuppliers, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuppliers = `-- name: CountSuppliers :one
SELECT COUNT(*) AS count
FROM suppliers
`

func (q *Queries) CountSuppliers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (name, contact_name, contact_email, contact_phone, address, meta)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
`

type CreateSupplierParams struct {
	Name         string      `json:"name"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	Address      pgtype.Text `json:"address"`
	Meta         []byte      `json:"meta"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Name,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
		arg.Meta,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM suppliers
WHERE id = $1
`

func (q *Queries) DeleteSupplier(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSupplier, id)
	return err
}

const getSupplierByEmail = `-- name: GetSupplierByEmail :one
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM suppliers
WHERE contact_email = $1
`

func (q *Queries) GetSupplierByEmail(ctx context.Context, contactEmail pgtype.Text) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByEmail, contactEmail)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM suppliers
WHERE id = $1
`

func (q *Queries) GetSupplierByID(ctx context.Context, id int32) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByName = `-- name: GetSupplierByName :one
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM suppliers
WHERE name = $1
`

func (q *Queries) GetSupplierByName(ctx context.Context, name string) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByName, name)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByPhone = `-- name: GetSupplierByPhone :one
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM suppliers
WHERE contact_phone = $1
`

func (q *Queries) GetSupplierByPhone(ctx context.Context, contactPhone pgtype.Text) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByPhone, contactPhone)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM suppliers
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSuppliersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Address,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSuppliers = `-- name: SearchSuppliers :many
SELECT id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
FROM suppliers
WHERE 
    ($3::TEXT IS NULL OR 
     name ILIKE '%' || $3 || '%' OR 
     contact_name ILIKE '%' || $3 || '%' OR 
     contact_email ILIKE '%' || $3 || '%' OR
     contact_phone ILIKE '%' || $3 || '%' OR
     address ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type SearchSuppliersParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Query  pgtype.Text `json:"query"`
}

func (q *Queries) SearchSuppliers(ctx context.Context, arg SearchSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, searchSuppliers, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Address,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET
    name = COALESCE(NULLIF($2, ''), name),
    contact_name = COALESCE($3, contact_name),
    contact_email = COALESCE($4, contact_email),
    contact_phone = COALESCE($5, contact_phone),
    address = COALESCE($6, address),
    meta = COALESCE($7, meta),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, contact_name, contact_email, contact_phone, address, meta, created_at, updated_at
`

type UpdateSupplierParams struct {
	ID           int32       `json:"id"`
	Column2      interface{} `json:"column_2"`
	ContactName  pgtype.Text `json:"contact_name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	ContactPhone pgtype.Text `json:"contact_phone"`
	Address      pgtype.Text `json:"address"`
	Meta         []byte      `json:"meta"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.ID,
		arg.Column2,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
		arg.Meta,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
