package views

import (
	"html/template"
	"net/http"
	"os"
	"path/filepath"

	"warehouse_system/internal/router"
)

// Auto-generated routes from templates
// DO NOT EDIT - Generated by: goengine render

var templates *template.Template

func init() {
	var err error
	// Create template with helper functions
	templates = template.New("").Funcs(template.FuncMap{
		"add": func(a, b int) int { return a + b },
		"sub": func(a, b int) int { return a - b },
		"mul": func(a, b int) int { return a * b },
		"div": func(a, b int) int {
			if b == 0 { return 0 }
			return a / b
		},
	})
	err = filepath.Walk("web/templates", func(path string, info os.FileInfo, err error) error {
		if err != nil { return err }
		if !info.IsDir() && filepath.Ext(path) == ".html" {
			templates, err = templates.ParseFiles(path)
			if err != nil { return err }
		}
		return nil
	})
	if err != nil { panic(err) }
}

// RenderDocs_docs handles /docs
func RenderDocs_docs(w http.ResponseWriter, r *http.Request) {
	if err := templates.ExecuteTemplate(w, "docs", nil); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// RegisterRoutes registers all template routes with the router
func RegisterRoutes(r router.Router) {
	r.Register(&router.Route{
		Method:      "GET",
		Path:        "/docs",
		Category:    "Templates",
		HandlerFunc: RenderDocs_docs,
		Input:       &router.RouteInput{RequiredAuth: false},
	})
}
