package routes

import (
	"warehouse_system/internal/handlers"
	"warehouse_system/internal/router"
	"warehouse_system/web/views"
)

// SetupRoutes registers all application routes
func SetupRoutes(r *router.RouterImpl) {
	// Health check route
	r.Register(&router.Route{
		Method:      "GET",
		Path:        "/health",
		HandlerFunc: handlers.HealthCheck,
		Category:    "system",
	})

	// Register template-based routes (generated by goengine render)
	views.RegisterRoutes(r)

	// Add more routes here
}
